
image:
    - Visual Studio 2017
    - Visual Studio 2019

platform:
    - x64
    - Win32

configuration:
    - Debug
    - Release

matrix:
  fast_finish: true

build_script:
- cmd: >-
    mkdir build && cd build && cmake -A %platform% .. && cmake --build . --config %configuration%

test_script:
- cmd: >-
    ctest -C %configuration%
